version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "trigger-S3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gi4qk2gsz79a"
s3_prefix = "trigger-S3"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "customstorageBucketName=\"mojimoji-voices\""

