version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pre-signed-url"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gi4qk2gsz79a"
s3_prefix = "pre-signed-url"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
